#!/usr/bin/env bash
GB_URL=$(grep -oP '(?<="gitBridgeInstanceUrl" : ")[^"]*' .gbmapping)
if [ -z "$GB_URL" ]
	then
	echo -e "Cannot find .gbMapping file.\nCheck if you are pushing a mapped branch."
	echo -e "Please check the documentation:"
	echo -e "http://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-endevor-software-change-manager/18-0/ca-endevor-scm-integrations-for-enterprise-devops/ca-endevor-scm-enterprise-git-bridge.html"
	exit 1
fi
DEBUG=false
$DEBUG && echo "DEBUG: Resolved gitBridgeInstanceUrl = $GB_URL"
curl -s -k "$GB_URL"/rest/evcs/v1/hooks/script/local > .git/scriptFile
bash .git/scriptFile $DEBUG $GB_URL
rtn_code=$?
rm .git/scriptFile
exit $rtn_code